### ISSUE TITLE
Only capital key controls work

### ISSUE THREAD

**Issue by interfect** [orlof/dcdos-edit#1]
In Lettuce, if you do, say, Ctrl + x (with no shift key, just the two keys), you get a character typed on the screen instead of a control sequence being detected.

If you do Ctrl + Shift + X, the control sequence registers.

**Comment by interfect** [comment]
It looks like the real issue here is that the editor is expecting to receive ASCII control characters (like 0x18), when the keyboard is sending normal characters and expecting the program to poll the modifier keys.

The [TC keyboard spec](https://github.com/techcompliant/TC-Specs/blob/master/Input/keyboard.md) says that characters are "fully translated" with regard to shift, but it doesn't say anything about control adding an offset down.

**Comment by interfect** [comment]
When I added code to my emulator to translate control characters, saving started working great. I think Lettuce doesn't do it, though.

**Comment by orlof** [comment]
I am still confused on how keyboard is supposed to work. I try to implement the code so that all reasonable interpretations of the spec should work.

Now I read the keyboard in smart mode. When I get the key I test for CTRL. If CTRL is pressed I 'and' the key with 9f. Now it should work with CTRL+x or CTRL+X.

Fixed in v1.02
