### ISSUE TITLE
Buffer too small

### ISSUE THREAD

**Issue by interfect** [orlof/dcdos-edit#3]
It looks like the buffer is only 4kb. The editor won't be able to load its own source code.

I can try pushing DC-DOS up if it needs more room.

**Comment by orlof** [comment]
4k was just randomly selected test value. I can safely increase it to 15k, but current version stores the editing buffer in program binary instead of initializing it to free memory. So the binary will be slower to load. 
...and even worse, the buffer size is reserved twice to be able to hold the worst case clipboard.

I will crank it up a bit and later refactor the buffer allocation.

**Comment by orlof** [comment]
changed to 16k in 1.01
